name: Bench

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  criterion:
    name: "Benchmarks (criterion)"
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: cargo bench
        run: cargo bench
