name: Hipparchus CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: llvm-tools-preview
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - name: Collect coverage data (including doctests)
      run: |
        cargo llvm-cov --no-report nextest
        cargo llvm-cov report --lcov --output-path lcov.info
    - name: Upload coverage data to codecov
      uses: codecov/codecov-action@v3
      with:
        files: lcov.info
