name: Hipparchus CI


on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: [cron: "20 20 * * 6"]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose